#include "/Engine/Private/Common.ush"

RWStructuredBuffer<float> CostArray;     
RWStructuredBuffer<float> Index;

[numthreads(1, 1, 1)]
void MainComputeShader(
	uint3 DispatchThreadId : SV_DispatchThreadID,
	uint GroupIndex : SV_GroupIndex )
{
	int WinIndex = -1;
	float WinCost = 99999;
	for(int i=0;i<FMMconst.rows;i++)
	{
		if(CostArray[i]<WinCost)
		{
			WinCost = CostArray[i];
			WinIndex = i;
		}
	}
	Index[0] = WinIndex;
}